spring:
  application:
    name: DungeonMastersFilms
  datasource:
    url: jdbc:h2:mem:peliculadb
    driverClassName: org.h2.Driver
    username: sa
    password: 

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always
